FROM node:20-alpine
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install drizzle-kit tsx drizzle-orm postgres @aws-sdk/client-s3

COPY db ./db
COPY i18n ./i18n
COPY drizzle.config.ts .
COPY tsconfig.json .
COPY env.ts .

# These will be overwritten by the real values at runtime
ARG S3_ENDPOINT="http://build-time-placeholder"
ARG S3_REGION="garage"
ARG S3_BUCKET="placeholder-bucket"
ARG S3_ACCESS_KEY_ID="placeholder-key"
ARG S3_SECRET_ACCESS_KEY="placeholder-secret"
ARG S3_FORCE_PATH_STYLE="true"

# Make them available to the build command
ENV S3_ENDPOINT=$S3_ENDPOINT
ENV S3_REGION=$S3_REGION
ENV S3_BUCKET=$S3_BUCKET
ENV S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID
ENV S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY
ENV S3_FORCE_PATH_STYLE=$S3_FORCE_PATH_STYLE

CMD ["sh", "-c", ". /secrets/s3.env && npm run setup"]